### Create a matrix

In [1]:
import numpy as np

In [2]:
#make a numpy array
a = np.arange(21,30)
print(a)

[21 22 23 24 25 26 27 28 29]


In [3]:
#Reshape the numpy array to 2d Matrix
a = np.arange(21,30).reshape(3,3) #3*3=9 elements in the original array(21,30)i.e 9
print(a)

[[21 22 23]
 [24 25 26]
 [27 28 29]]


In [5]:
#take the transpose of the matrix
b = np.transpose(a)
print(b)
#rows converted to columns and viceversa

[[21 24 27]
 [22 25 28]
 [23 26 29]]


In [6]:
#Multiply matrices
c = np.dot(a,b)
print(c)

[[1454 1652 1850]
 [1652 1877 2102]
 [1850 2102 2354]]


In [9]:
#Make new matrices and multiply
a = np.arange(1,10).reshape(3,3)#9 elements reshaped
b = np.arange(1,7).reshape(3,2)#6 elements reshaped

#remember for multiplication, First matrix Cols = Second Matrix Rows

c = np.dot(a,b)
d = a.dot(b)#another way

print("First matrix",a)
print("Second matrix",b)
print('Multiplication c',c)
print('Multiplication d',d)

First matrix [[1 2 3]
 [4 5 6]
 [7 8 9]]
Second matrix [[1 2]
 [3 4]
 [5 6]]
Multiplication c [[ 22  28]
 [ 49  64]
 [ 76 100]]
Multiplication d [[ 22  28]
 [ 49  64]
 [ 76 100]]


In [10]:
#Matrix Multiplication is assosciative
#i.e. (AB)C=A(BC)
A = np.arange(1,10).reshape(3,3)#9 elements
B = np.arange(1,7).reshape(3,2)#6 elements
C = np.arange(1,5).reshape(2,2)#4 elements

#(AB)C
Prod1 = (A.dot(B)).dot(C)
Prod2 = A.dot(B.dot(C))

print("Prod1 is",Prod1)
print("Prod2 is",Prod2)



Prod1 is [[106 156]
 [241 354]
 [376 552]]
Prod2 is [[106 156]
 [241 354]
 [376 552]]


In [13]:
#Matrix multiplication is not cumulative. Means the result of A(B) is not equal to B(A )
A = np.arange(1,10).reshape(3,3)#9 elements
B = np.arange(1,7).reshape(3,2)#6 elements


#(AB)C
Prod1 = A.dot(B)
Prod2 = B.dot(A)#This will result in an error as the no. of cols in B is not equal to np. of rows in A

print("Prod1 is",Prod1)
print("Prod2 is",Prod2)

Prod1 is [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
Prod2 is [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [18]:
#Find inverse of a matrix 

#1. Find row Echolon matrix : manipulate rows of matrix till you get identity matrix(i.e. all 1s across the diagonal)
#2nd Way
#2a. find determinant of a matrix( applied to square matrix only). Prints the submatrices with associated signs of indices i.e. ad-bc

#determinant
A = np.arange(1,5).reshape(2,2)
B = np.linalg.det(A)
C = np.arange(1,10).reshape(3,3)
D = np.linalg.det(C)

print("Original 2x2 matrix A",A)
print("Determinant of matrix A is",B)

print("Original 3*3 matrix C",C)
print("Determinant of matrix C is",D)

#A=([[1,2],[3,4]]) i.e. 1*4-2*3=-2 and that is the determinant of the square matrix
#A=([[1,2,3],[4,5,6],[7,8,9]]) = 1|5*9-6*8| - 2|4*9-6*7| + 3|4*8-5*7|


Original 2x2 matrix A [[1 2]
 [3 4]]
Determinant of matrix A is -2.0000000000000004
Original 3*3 matrix C [[1 2 3]
 [4 5 6]
 [7 8 9]]
Determinant of matrix C is -9.51619735392994e-16


In [ ]:
#2b. Calculate Minor of a matrix(submatrices)
#2c. Cofactor of a matrix( as per the + and - signs)
#2d. Cofactor matrix( multiply abve matrix with cofactor signs)
#2e. Adjunt of a matrix( Transpose this Cofactor matrix)

#Inverse of a matrix= Multiply Adjunt of Matrix by Determinant of matrix(calculated in last step)

In [22]:
#Code for inverse matrix so simple in Numpy
A = np.arange(1,10).reshape(3,3)
A1 = np.linalg.inv(A)


print("Original Matrix A is ",A)
print("Inverse of matrix A is ",A1)

#Let's check if the product of A and it's inverse A1 comes out to be a identity matrix

C = A.dot(A1)
print("product of A and its inverse A1 is ",C)


Original Matrix A is  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Inverse of matrix A is  [[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
product of A and its inverse A1 is  [[ 0.   1.  -0.5]
 [ 0.   2.  -1. ]
 [ 0.   3.   2.5]]


In [24]:
#Find eigen vectors using python. These vectors remain unchanged even after linear transformation on the array

A = np.arange(21,30).reshape(3,3)#9 elements
B = np.linalg.eig(A)

print("Original Matrix is",A)
print("Eigen vector is",B)




Original Matrix is [[21 22 23]
 [24 25 26]
 [27 28 29]]
Eigen vector is (array([ 7.52392369e+01, -2.39236876e-01,  2.99268899e-15]), array([[-0.50588144, -0.72551862,  0.40824829],
       [-0.57461613, -0.01878627, -0.81649658],
       [-0.64335081,  0.68794608,  0.40824829]]))


In [ ]:
#we have already made a project on PCA and eigen values